/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JOptionPane;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Cynthia
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Experto - Test Vocacional ITCH");
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Bienvenido al test vocacional ITCH");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciar-la-reproduccion-de-medios-icono-7675-32.png"))); // NOI18N
        jButton1.setText("EMPEZAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/liberar-icono-6437-32.png"))); // NOI18N
        jButton2.setText("SALIR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Con la finalidad de orientar al alumno a ingresar a la institucional se proporciona un test vocacional para que de acuerdo a sus gustos, aptitudes ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("y habilidades decida por alguna de las carreras que oferta el Instituto Tecnologico de Chilpancingo");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(105, 105, 105)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
       int preguntaCivil,preguntaSistemas,preguntaInformatica,preguntaGestion,preguntaContabilidad;
       
       preguntaCivil = JOptionPane.showConfirmDialog(rootPane, "¿Tiene algun gusto por la el diseño y construccion de edificios?", null, ConfirmationCallback.YES_NO_OPTION);
       if(preguntaCivil==0){
           ingCivil();
       }else if(preguntaCivil==1){
                   
                   preguntaSistemas=JOptionPane.showConfirmDialog(rootPane, "¿Tiene algun gusto por desarrollar aplicaciones web, movil o de escritorio?",null,ConfirmationCallback.YES_NO_OPTION);
                   if(preguntaSistemas==0){
                       ingSistemas();
                   }else if(preguntaSistemas==1){
                       preguntaInformatica=JOptionPane.showConfirmDialog(rootPane, "¿Tiene algun gusto por administrar los recursos de las TIC´s?",null,ConfirmationCallback.YES_NO_OPTION);
                       if(preguntaInformatica==0){
                           ingInformatica();
                       }else if(preguntaInformatica==1){
                           preguntaGestion=JOptionPane.showConfirmDialog(rootPane,"¿Tiene algun gusto por realizar estrategias que ayuden a contruir o iniciar una empresa? ", null, ConfirmationCallback.YES_NO_OPTION);
                            if(preguntaGestion==0){
                                ingGestion();
                            }else if(preguntaGestion==1){
                                preguntaContabilidad=JOptionPane.showConfirmDialog(rootPane,"¿Tienes algun gusto por el estado financiero de una empresa, organizacion o persona?", null, ConfirmationCallback.YES_NO_OPTION);
                                if(preguntaContabilidad==0){
                                    contabilidad();
                                }else{
                                    JOptionPane.showMessageDialog(rootPane, "La institucion no cuenta con alguna carrera de acuerdo a su perfil, vuelva a intentarlo ");
                                }
                            }
                       } 
                   }
       }
       
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MousePressed
public void ingCivil(){
    int p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,contadorCivil=0;
    
    p1=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habiliadade para diseñar ?",null,ConfirmationCallback.YES_NO_OPTION);
        if(p1==0){
            contadorCivil++;  }  
            p2=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría tener clases de campo(fuera de aulas)?",null,ConfirmationCallback.YES_NO_OPTION);
            if(p2==0){
                contadorCivil++;}
                p3=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habiliades para las matematicas?",null,ConfirmationCallback.YES_NO_OPTION);
                if(p3==0){
                    contadorCivil++;}
                    p4=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría conocer la mecanica de materiales?",null,ConfirmationCallback.YES_NO_OPTION);
                    if(p4==0){
                        contadorCivil++;}
                        p5=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para el calculo(Diferencial,Integral,Vectorial)?",null,ConfirmationCallback.YES_NO_OPTION);
                        if(p5==0){
                            contadorCivil++;}
                            p6=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría tener experiencia en la instalacion de edificios?",null,ConfirmationCallback.YES_NO_OPTION);
                            if(p6==0){
                                contadorCivil++;}
                                p7=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría dirigir y participar en estudios para determinar la factibilidad ambiental, económica, técnica y financiera de los proyectos de obras civiles.?",null,ConfirmationCallback.YES_NO_OPTION);
                                if(p7==0){
                                    contadorCivil++;}
                                    p8=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Optimizar el uso de los recursos en los procesos constructivos de obras civiles?",null,ConfirmationCallback.YES_NO_OPTION);
                                    if(p8==0){
                                        contadorCivil++;}
                                        p9=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría emplear técnicas de control de calidad en los materiales y procesos constructivos.?",null,ConfirmationCallback.YES_NO_OPTION);
                                        if(p9==0){
                                            contadorCivil++;}
                                             p10=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría utilizar las TIC's ,software y herramientas electrónicas para la Ingeniería Civil?",null,ConfirmationCallback.YES_NO_OPTION);
                                             if(p10==0){
                                                 contadorCivil++;}
                                                 p11=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaria Planear, proyectar, diseñar, construir, operar y conservar Obras Hidráulicas?",null,ConfirmationCallback.YES_NO_OPTION);
                                                 if(p11==0){
                                                     contadorCivil++;}
                                                     p12=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría construir, operar y conservar obras sanitarias?",null,ConfirmationCallback.YES_NO_OPTION);
                                                     if(p12==0){
                                                         contadorCivil++;}
                                                         p13=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría proyectar, diseñar, construir, operar y conservar Sistemas Estructurales, Vías Terrestres y Edificación ?",null,ConfirmationCallback.YES_NO_OPTION);
                                                         if(p13==0){
                                                             contadorCivil++;}
                                                             p14=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para el analisis de problemas relacionados con obras civiles?",null,ConfirmationCallback.YES_NO_OPTION);
                                                             if(p14==0){
                                                                 contadorCivil++;}
                                                                 p15=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría estudiar Ingenieria Civil?",null,ConfirmationCallback.YES_NO_OPTION);
                                                                 if(p15==0){
                                                                     contadorCivil++;}
                                                                 
   
    int multiplicacion = (10 * contadorCivil);
    int porcentaje =((multiplicacion * 100)/150);
    if(porcentaje < 50){
        ingSistemas();
    }else{
       JOptionPane.showMessageDialog(null,"RESULTADO:\n De acuerdo a las preguntas contestadas anteriormente\n"+
                                                        "usted tiene cualidades y aptitudes que corresponden\n"+
                                                        "a una de nuestras carreras que oferta el ITCH:\n\n"+
                                                        "INGENERIA CIVIL\n\n"+
                                                        "con un porcentaje de:"+porcentaje+"%"); 
    }
    

}
public void ingSistemas(){
    int p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,contadorSistemas=0;
    
    p1=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habiliadades para programacion?",null,ConfirmationCallback.YES_NO_OPTION);
        if(p1==0){
            contadorSistemas++;  }  
            p2=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría tener clases en un laboratorio de computo?",null,ConfirmationCallback.YES_NO_OPTION);
            if(p2==0){
                contadorSistemas++;}
                p3=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para las matematicas?",null,ConfirmationCallback.YES_NO_OPTION);
                if(p3==0){
                    contadorSistemas++;}
                    p4=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría desarollar aplicaciones móviles?",null,ConfirmationCallback.YES_NO_OPTION);
                    if(p4==0){
                        contadorSistemas++;}
                        p5=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para el calculo(Diferencial,Integral,Vectorial)?",null,ConfirmationCallback.YES_NO_OPTION);
                        if(p5==0){
                            contadorSistemas++;}
                            p6=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría tener experiencia en la instalacion de cableado de red de alguna infraestructura?",null,ConfirmationCallback.YES_NO_OPTION);
                            if(p6==0){
                                contadorSistemas++;}
                                p7=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría diseñar, configurar y administrar redes computacionales\n aplicando las normas y estándares vigentes?",null,ConfirmationCallback.YES_NO_OPTION);
                                if(p7==0){
                                    contadorSistemas++;}
                                    p8=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Desarrollar, implementar y administrar software de sistemas\n o de aplicación que cumpla con los estándares de calidad con el fin de apoyar la productividad y competitividad de las organizaciones?",null,ConfirmationCallback.YES_NO_OPTION);
                                    if(p8==0){
                                        contadorSistemas++;}
                                        p9=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría diseñar e implementar interfaces hombre-máquina y máquina-máquina\n para la automatización de sistemas?",null,ConfirmationCallback.YES_NO_OPTION);
                                        if(p9==0){
                                            contadorSistemas++;}
                                             p10=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Identificar y comprender las tecnologías de hardware para\n proponer, desarrollar y mantener aplicaciones eficientes?",null,ConfirmationCallback.YES_NO_OPTION);
                                             if(p10==0){
                                                 contadorSistemas++;}
                                                 p11=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaria Diseñar, desarrollar y administrar bases de datos conforme a requerimientos definidos,\n"+
                                                                                             "normas organizacionales de manejo y seguridad de la información, utilizando tecnologías emergentes.?",null,ConfirmationCallback.YES_NO_OPTION);
                                                 if(p11==0){
                                                     contadorSistemas++;}
                                                     p12=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría analizar un problema y diseñar la Base de datos ?",null,ConfirmationCallback.YES_NO_OPTION);
                                                     if(p12==0){
                                                         contadorSistemas++;}
                                                         p13=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría desarrollar aplicaciones de ambito web?",null,ConfirmationCallback.YES_NO_OPTION);
                                                         if(p13==0){
                                                             contadorSistemas++;}
                                                             p14=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para el analisis de problemas relacionados con matematicas, fisica, quimica?",null,ConfirmationCallback.YES_NO_OPTION);
                                                             if(p14==0){
                                                                 contadorSistemas++;}
                                                                 p15=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría estudiar Ingenieria en Sistemas Computacionales?",null,ConfirmationCallback.YES_NO_OPTION);
                                                                 if(p15==0){
                                                                     contadorSistemas++;}
                                                                 
   
    int multiplicacion = (10 * contadorSistemas);
    double porcentaje =((multiplicacion * 100)/150);
    if(porcentaje < 50){
        ingInformatica();
    }else{
       JOptionPane.showMessageDialog(null,"RESULTADO:\n De acuerdo a las preguntas contestadas anteriormente\n"+
                                                        "usted tiene cualidades y aptitudes que corresponden\n"+
                                                        "a una de nuestras carreras que oferta el ITCH:\n\n"+
                                                        "INGENERIA EN SISTEMAS COMPUTACIONALES\n\n"+
                                                        "Con un porcentaje de:%"+porcentaje); 
    }
    

}
public void ingInformatica(){
    int p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,contadorInformatica=0;
    
    p1=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para formular, gestionar y evaluar el desarrollo de proyectos informáticos en las organizaciones?",null,ConfirmationCallback.YES_NO_OPTION);
        if(p1==0){
            contadorInformatica++;  }  
            p2=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría tener clases en un laboratorio de computo?",null,ConfirmationCallback.YES_NO_OPTION);
            if(p2==0){
                contadorInformatica++;}
                p3=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para las matematicas?",null,ConfirmationCallback.YES_NO_OPTION);
                if(p3==0){
                    contadorInformatica++;}
                    p4=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Aplicar normas, marcos de referencia,\n"+
                                                              " estándares de calidad y seguridad vigentes en el ámbito\n"+
                                                              " del desarrollo y gestión de tecnologías y sistemas de información.?",null,ConfirmationCallback.YES_NO_OPTION);
                    if(p4==0){
                        contadorInformatica++;}
                        p5=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para el calculo(Diferencial,Integral,Vectorial)?",null,ConfirmationCallback.YES_NO_OPTION);
                        if(p5==0){
                            contadorInformatica++;}
                            p6=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría realizar actividades de auditoría y consultoría relacionadas con la función informática?",null,ConfirmationCallback.YES_NO_OPTION);
                            if(p6==0){
                                contadorInformatica++;}
                                p7=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Identificar y aplicar modelos pertinentes en el diseño e implementación\n de base de datos para la gestión de la información en las organizaciones.?",null,ConfirmationCallback.YES_NO_OPTION);
                                if(p7==0){
                                    contadorInformatica++;}
                                    p8=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Desarrollar, implementar y administrar software de sistemas\n o de aplicación que cumpla con los estándares de calidad con el fin de apoyar la productividad y competitividad de las organizaciones?",null,ConfirmationCallback.YES_NO_OPTION);
                                    if(p8==0){
                                        contadorInformatica++;}
                                        p9=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Comunicarse de manera efectiva, en su propio idioma y al menos\n en un idioma extranjero, para integrarse a un contexto globalizado, en su desarrollo personal y profesional.?",null,ConfirmationCallback.YES_NO_OPTION);
                                        if(p9==0){
                                            contadorInformatica++;}
                                             p10=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Crear y administrar redes de comunicación, que contemplen el diseño,\n selección, instalación y mantenimiento para la operación de equipos de cómputo, aprovechando los avances tecnológicos a su alcance.?",null,ConfirmationCallback.YES_NO_OPTION);
                                             if(p10==0){
                                                 contadorInformatica++;}
                                                 p11=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaria Observar y fomentar el cumplimiento de las disposiciones\n de carácter legal, relacionadas con la función informática.",null,ConfirmationCallback.YES_NO_OPTION);
                                                 if(p11==0){
                                                     contadorInformatica++;}
                                                     p12=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Analizar, desarrollar y programar modelos matemáticos, estadísticos y de simulación.?",null,ConfirmationCallback.YES_NO_OPTION);
                                                     if(p12==0){
                                                         contadorInformatica++;}
                                                         p13=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Análizar y Modelar Sistemas de Información?",null,ConfirmationCallback.YES_NO_OPTION);
                                                         if(p13==0){
                                                             contadorInformatica++;}
                                                             p14=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades el emsamble y desamble de un equipo de computo?",null,ConfirmationCallback.YES_NO_OPTION);
                                                             if(p14==0){
                                                                 contadorInformatica++;}
                                                                 p15=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría estudiar Ingenieria en Informatica?",null,ConfirmationCallback.YES_NO_OPTION);
                                                                 if(p15==0){
                                                                     contadorInformatica++;}
                                                                 
   
    int multiplicacion = (10 * contadorInformatica);
    int porcentaje =((multiplicacion * 100)/150);
    if(porcentaje < 50){
        ingGestion();
    }else{
       JOptionPane.showMessageDialog(null,"RESULTADO:\n De acuerdo a las preguntas contestadas anteriormente\n"+
                                                        "usted tiene cualidades y aptitudes que corresponden\n"+
                                                        "a una de nuestras carreras que oferta el ITCH:\n\n"+
                                                        "INGENERIA EN INFORMATICA\n\n"+
                                                        "Con un porcentaje de:%"+porcentaje); 
    }
    

}
public void ingGestion(){
    int p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,contadorGestion=0;
    
    p1=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para Desarrollar y aplicar habilidades directivas y la ingeniería en el diseño,\n"+
                                              " creación, gestión, desarrollo, fortalecimiento e innovación de las organizaciones, con una orientación\n"+
                                              " sistémica y sustentable para la toma de decisiones en forma efectiva?",null,ConfirmationCallback.YES_NO_OPTION);
        if(p1==0){
            contadorGestion++;  }  
            p2=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Diseñar e innovar estructuras administrativas y procesos, con base en las necesidades de las\n"+
                                                      " organizaciones para competir eficientemente en mercados globales.?",null,ConfirmationCallback.YES_NO_OPTION);
            if(p2==0){
                contadorGestion++;}
                p3=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para las matematicas?",null,ConfirmationCallback.YES_NO_OPTION);
                if(p3==0){
                    contadorGestion++;}
                    p4=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Gestionar eficientemente los recursos de la organización\n"+
                                                              " con visión compartida, con el fin de suministrar bienes y servicios de calidad?",null,ConfirmationCallback.YES_NO_OPTION);
                    if(p4==0){
                        contadorGestion++;}
                        p5=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para el calculo(Diferencial,Integral,Vectorial)?",null,ConfirmationCallback.YES_NO_OPTION);
                        if(p5==0){
                            contadorGestion++;}
                            p6=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Aplicar métodos cuantitativos y cualitativos para el análisis e interpretación de datos y\n"+
                                                                      " modelado de sistemas, en los procesos organizacionales para la mejora continua, atendiendo estándares de\n"+
                                                                      " calidad mundial.?",null,ConfirmationCallback.YES_NO_OPTION);
                            if(p6==0){
                                contadorGestion++;}
                                p7=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Diseñar, evaluar y emprender nuevos negocios y proyectos empresariales, que promuevan\n"+
                                                                          " el desarrollo sustentable y la responsabilidad social, en un mercado competitivo.?",null,ConfirmationCallback.YES_NO_OPTION);
                                if(p7==0){
                                    contadorGestion++;}
                                    p8=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Diseñar e implementar estrategias de mercadotecnia basadas en información recopilada\n "+
                                                                              "de fuentes primarias y secundarias del consumidor o usuario de algún producto, de acuerdo a oportunidades\n"+
                                                                              " y amenazas del mercado?",null,ConfirmationCallback.YES_NO_OPTION);
                                    if(p8==0){
                                        contadorGestion++;}
                                        p9=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Establecer programas para el fortalecimiento de la seguridad e\n"+
                                                                                  " higiene en las organizaciones.?",null,ConfirmationCallback.YES_NO_OPTION);
                                        if(p9==0){
                                            contadorGestion++;}
                                             p10=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Interpretar y aplicar normas legales que incidan\n en la creación y desarrollo de las organizaciones.?",null,ConfirmationCallback.YES_NO_OPTION);
                                             if(p10==0){
                                                 contadorGestion++;}
                                                 p11=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaria Integrar, dirigir y desarrollar equipos de trabajo para la mejora continua y\n el crecimiento integral de las organizaciones.",null,ConfirmationCallback.YES_NO_OPTION);
                                                 if(p11==0){
                                                     contadorGestion++;}
                                                     p12=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Analizar, desarrollar y programar modelos matemáticos, estadísticos y de simulación.?",null,ConfirmationCallback.YES_NO_OPTION);
                                                     if(p12==0){
                                                         contadorGestion++;}
                                                         p13=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Analizar e interpretar la información financiera para detectar oportunidades de mejora e\n"+
                                                                                                    " inversión en un mundo global, que incidan en la rentabilidad del negocio.?",null,ConfirmationCallback.YES_NO_OPTION);
                                                         if(p13==0){
                                                             contadorGestion++;}
                                                             p14=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habilidades para ultilizar las nuevas tecnologías de información en la organización,\n"+
                                                                                                        " para optimizar los procesos de comunicación y eficientar la toma de decisiones.?",null,ConfirmationCallback.YES_NO_OPTION);
                                                             if(p14==0){
                                                                 contadorGestion++;}
                                                                 p15=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría estudiar Ingenieria en Gestion Empresarial?",null,ConfirmationCallback.YES_NO_OPTION);
                                                                 if(p15==0){
                                                                     contadorGestion++;}
                                                                 
   
    int multiplicacion = (10 * contadorGestion);
    int porcentaje =((multiplicacion * 100)/150);
    if(porcentaje < 50){
        contabilidad();
    }else{
       JOptionPane.showMessageDialog(null,"RESULTADO:\n De acuerdo a las preguntas contestadas anteriormente\n"+
                                                        "usted tiene cualidades y aptitudes que corresponden\n"+
                                                        "a una de nuestras carreras que oferta el ITCH:\n\n"+
                                                        "INGENERIA EN IGESTION EMPRESARIAL\n\n"+
                                                        "Con un porcentaje de:%"+porcentaje); 
    }
    

}
public void contabilidad(){
    int p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,i=0;
    
    p1=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habiliadade para Diseñar, implantar, controlar, evaluar, asesorar e\n"+
                                              " innovar sistemas de información financiera, administrativa, fiscal y de auditoría\n"+
                                              " en entidades económicas ?",null,ConfirmationCallback.YES_NO_OPTION);
        if(p1==0){
            i++;  }  
            p2=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Analizar y generar información financiera con apego a las Normas de Información Financiera,\n"+
                                                      " nacionales e internacionales, para la toma de decisiones.?",null,ConfirmationCallback.YES_NO_OPTION);
            if(p2==0){
                i++;}
                p3=JOptionPane.showConfirmDialog(rootPane,"¿Tienes habiliades para las matematicas?",null,ConfirmationCallback.YES_NO_OPTION);
                if(p3==0){
                    i++;}
                    p4=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Auditar sistemas financieros, fiscales y administrativos de las entidades económicas con\n"+
                                                              " apego a las Normas y Procedimientos de Auditoria y Normas para Atestiguar.?",null,ConfirmationCallback.YES_NO_OPTION);
                    if(p4==0){
                        i++;}
                        p5=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Aplicar el marco legal pertinente a las características y necesidades de la entidad económica dentro del campo profesional.?",null,ConfirmationCallback.YES_NO_OPTION);
                        if(p5==0){
                            i++;}
                            p6=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Administrar estratégicamente los recursos de las entidades económicas con visión emprendedora y competitiva?",null,ConfirmationCallback.YES_NO_OPTION);
                            if(p6==0){
                                i++;}
                                p7=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Utilizar las Tecnologías de Información y Comunicación para eficientar los procesos y la toma de decisiones.?",null,ConfirmationCallback.YES_NO_OPTION);
                                if(p7==0){
                                    i++;}
                                    p8=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Desarrollar investigación asumiendo una actitud de liderazgo, compromiso y servicio con su entorno social.?",null,ConfirmationCallback.YES_NO_OPTION);
                                    if(p8==0){
                                        i++;}
                                        p9=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Elaborar y evaluar proyectos de inversión de acuerdo a las características y\n"+
                                                                                  " necesidades del entorno y propiciar la generación de empresas.?",null,ConfirmationCallback.YES_NO_OPTION);
                                        if(p9==0){
                                            i++;}
                                             p10=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Formar y promover el desarrollo de grupos de trabajo interdisciplinarios\n"+
                                                                                        " para el logro de los resultados de las entidades con un sentido de responsabilidad social y\n"+
                                                                                        " visión integradora.?",null,ConfirmationCallback.YES_NO_OPTION);
                                             if(p10==0){
                                                 i++;}
                                                 p11=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaria Conocer y proponer estrategias de mercadotecnia \n"+
                                                                                            "que permitan alcanzar los objetivos de la empresa.?",null,ConfirmationCallback.YES_NO_OPTION);
                                                 if(p11==0){
                                                     i++;}
                                                     p12=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría Aplicar métodos de análisis de información financiera para\n"
                                                                                               +" determinar las mejores alternativas de inversión y financiamiento.?",null,ConfirmationCallback.YES_NO_OPTION);
                                                     if(p12==0){
                                                         i++;}
                                                         p13=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría administrar la producccion y operacion de una empresa?",null,ConfirmationCallback.YES_NO_OPTION);
                                                         if(p13==0){
                                                             i++;}
                                                             p14=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaria elaborar y evaluar proyectos de inversion?",null,ConfirmationCallback.YES_NO_OPTION);
                                                             if(p14==0){
                                                                 i++;}
                                                                 p15=JOptionPane.showConfirmDialog(rootPane,"¿Te gustaría estudiar Contador Publico?",null,ConfirmationCallback.YES_NO_OPTION);
                                                                 if(p15==0){
                                                                     i++;}
                                                                 
   
    int multiplicacion = (10 * i);
    int porcentaje =((multiplicacion * 100)/150);
    if(porcentaje < 50){
       JOptionPane.showMessageDialog(rootPane, "La institucion no cuenta con alguna carrera de acuerdo a su perfil, vuelva a intentarlo ");
                               
    }else{
       JOptionPane.showMessageDialog(null,"RESULTADO:\n De acuerdo a las preguntas contestadas anteriormente\n"+
                                                        "usted tiene cualidades y aptitudes que corresponden\n"+
                                                        "a una de nuestras carreras que oferta el ITCH:\n\n"+
                                                        "CONTADOR PUBLICO\n\n"+
                                                        "con un porcentaje de:%"+porcentaje); 
    }
    

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
